### ISSUE TITLE
[Feature Request] Implementation of syscall 9

### ISSUE THREAD

**Issue by Cardosaum** [LeoRiether/FPGRARS#12]
Hi!

First of all, I'd like to thank you for such an amazing project. it's extremely useful.

I'm creating this issue just to know if would be feasible to implement the
syscall 9 (sbrk).

This function is similar, in concept, to C's `malloc`. Without it I'm unable to
dynamically create arrays/structs etc in run-time.

Thanks in advance! :)

**Comment by LeoRiether** [comment]
Hello! 

Thank you for the request, I just added it in 5b2c6ea97975df34757fb9ddd253ad7a15d98855, please check the [latest release](https://github.com/LeoRiether/FPGRARS/releases/tag/v1.9) and let me know if you find any bugs.

**Comment by Cardosaum** [comment]
Wow!!!

I can't thank you enough. You are absolutely AMAZING. 

It's working like a charm now.

Thanks! 😄
