### ISSUE TITLE
No transparency while using read syscall

### ISSUE THREAD

**Issue by davipatury** [LeoRiether/FPGRARS#17]
When writing an image to Bitmap Display memory using open syscall (1024) and read syscall (63), the output doesn't ignore the `0xC7` pixels.

**Comment by LeoRiether** [comment]
I tried fixing this, but ended up with something visibly slower... WIP :)

**Comment by LeoRiether** [comment]
This should be fixed in [v1.11.0](https://github.com/LeoRiether/FPGRARS/releases/tag/v1.11.0). Can you confirm it works on your side?

**Comment by davipatury** [comment]
I'm not at home right now, but I'll test it as soon as possible.
