### ISSUE TITLE
Macros with .data definitions can only be used once

### ISSUE THREAD

**Issue by qrno** [LeoRiether/FPGRARS#18]
The following macro causes problems when called more than once. The second call's .data supersedes the first and in the final program "lemon" is printed twice.

```assembly
.macro print_string(%str)
.data
var: .string %str

.text
    li a7 4
    la a0 var
    ecall
.end_macro

.text
    print_string("apple")
    print_string("lemon")
```

RARS solves this problem by adding a _M{#} suffix to the .data definitions inside of macros, so that the macros above would define var_M0 and var_M1 respectively. This counter is global, if a different macro call also defines var, it'll call it var_M2.

**Comment by LeoRiether** [comment]
Wow I had no idea you could do that!

**Comment by LeoRiether** [comment]
Update more than a year later: this will be fixed in the new parser rewrite 🎉
