### ISSUE TITLE
Read ecall is slow in v1.11

### ISSUE THREAD

**Issue by ziul123** [LeoRiether/FPGRARS#20]
The following code plays the video in video.bin in 25 fps. Using release v1.10.6, the video was played almost perfectly in sync with the original on [youtube](https://www.youtube.com/watch?v=FtutLA63Cp8). However, with the latest release, it plays a lot slower. This is not due to the time it takes to actually execute the instructions, since decreasing the milliseconds waited makes it faster.
```
.data 

SL:		.string "video.bin"

.text

	li s0,0xFF000000	#inicio da frame 0
	li s1,0xFF100000	#inicio da frame 1
	li s2,76800			#tamanho da frame
	li s3,0xFF200604	#selecionador de frame
	
	la a0,SL
	li a1,0
	li a7,1024
	ecall				#open
	mv s4,a0			#s4 tem o video sem legenda

LOOP:
	csrr t1,3073
	sub t1,t1,s11
	li t2,40		#video de 25 fps -> 1 frame cada 40 ms
	bltu t1,t2,LOOP
	
	
	mv a0,s4
	mv a1,s0
	mv a2,s2		#tamanho da frame
	li a7,63
	ecall			#read video sem legenda no frame 0

	csrr s11,3073
	bltz a0,END
	j LOOP

END:
	mv a0,s3
	li a7,57
	ecall


	li a7,10
	ecall
```
The file video.bin is in the attached .zip file.
[video.zip](https://github.com/LeoRiether/FPGRARS/files/7116938/video.zip)

**Comment by LeoRiether** [comment]
I guess the changes made in cff7d6dd9c are too slow for this... Reading from a file in v1.10 was a simple `file.read(memory)`, but that copied `0xC7` (transparent) bytes as magenta onto the video memory, so in v1.11 I check every byte of the file for `0xC7`s, which is way slower. I'll try to optimize it as soon as possible!

PS: I'm glad someone's using FPGRARS for the right use case.
