### ISSUE TITLE
Wrong print float syscall number

### ISSUE THREAD

**Issue by davipatury** [LeoRiether/FPGRARS#21]
According to the [supported ecalls table](https://github.com/LeoRiether/FPGRARS#supported-ecalls), in FPGRARS the print float syscall number is `6`.
But in [RARS](https://github.com/TheThirdOne/rars/wiki/Environment-Calls), the print float syscall number is `2` (and *read* float is number `6`).

**Comment by LeoRiether** [comment]
Nice catch. Fixed in ecc9b1a
