### ISSUE TITLE
Bug: Clicking on the window bar crashes 

### ISSUE THREAD

**Issue by d-magit** [LeoRiether/FPGRARS#25]
Clicking on the display's window bar instantly kills the program
![image](https://user-images.githubusercontent.com/48662592/133909634-6bfa952d-f21e-4aaf-a02b-41844dad5af5.png)

**Comment by LeoRiether** [comment]
Apparently this is related to https://github.com/rust-windowing/winit/issues/1466. It seems that updating `pixel-canvas` fixes it, at least on my machine.

I just released [v1.13.1](https://github.com/LeoRiether/FPGRARS/releases/tag/v1.13.1), could you confirm that it works there as well?

**Comment by d-magit** [comment]
Oooh yeah okay, that seems to fix it. Sorry, I hadn't seen that there was already an issue addressing this

**Comment by LeoRiether** [comment]
I found that issue looking a solution for the issue you posted, actually :)

**Comment by d-magit** [comment]
Oooh! I'm glad to know then hahah :D
